### ISSUE TITLE
Nitro 2.8 release

### ISSUE THREAD

**Issue by PaulBellefleur** [mdaus/nitro#113]
Hey I was wondering when your next public release is? 2.7 is pretty old and I would like a stable build.

**Comment by asylvest** [comment]
Hey Paul - we've been doing NITRO releases on an ad hoc basis... basically either when a major bug is found, feature is added, or upon user request.  We do consider the master branch stable, but I understand wanting a formal release.  We'll try to put one together in the next few weeks - this'll mostly be organizing release notes and buttoning up a few things, so shouldn't be a major effort.  Will keep you posted.

**Comment by PaulBellefleur** [comment]
Awesome thank you so much!

**Comment by asylvest** [comment]
@JonathanMeans turned "next few weeks" into "next day" - release is ready: https://github.com/mdaus/nitro/releases/tag/NITRO-2.8

**Comment by TorbenDyrby** [comment]
Can you make a win64 installer, please?
When I run the win32 installer, I dont get the "share" folder. The 2.7 does have the "share" folder, but it is made for python 2.x (I'm on 3.7).
Thanks.

**Comment by JonathanMeans** [comment]
@asylvest Do you know of a way to force a win64 build? I tried configuring with `--enable-64bit`, but it doesn't seem to do anything obvious in the configure output.

**Comment by TorbenDyrby** [comment]
I’m sorry, I have no idea how to build :-(

Who build the 2.7? Perhaps he can help?

Further, if I install the win32, I don’t get the python bindings (the share folder). Perhaps it’s because I am on win10...

Regards Torben

Sent from my wireless device

**Comment by JonathanMeans** [comment]
@TorbenDyrby I've updated the 2.8 release with a Win64 installer that should include Python bindings compatible with 3.x. Does this meet your needs?

**Comment by JonathanMeans** [comment]
Actually... hang on a minute. One more thing I need to update.

**Comment by JonathanMeans** [comment]
Alright, try it now

**Comment by TorbenDyrby** [comment]
Thanks s lot!

The share folder with python is now installed, but I get some errors trying to import, see below. I am new to python, so it could be, that I am missing some setup. 

>>> import nitf
Traceback (most recent call last):
  File "C:\apps\nitro-nitf\share\python\nitf\nitropy.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\apps\Miniconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\apps\nitro-nitf\share\python\nitf\__init__.py", line 29, in <module>
    import nitf.nitropy
  File "C:\apps\nitro-nitf\share\python\nitf\nitropy.py", line 17, in <module>
    _nitropy = swig_import_helper()
  File "C:\apps\nitro-nitf\share\python\nitf\nitropy.py", line 16, in swig_import_helper
    return importlib.import_module('_nitropy')
  File "C:\apps\Miniconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_nitropy'

Sent from my wireless device

**Comment by JonathanMeans** [comment]
Can I see your `LD_LIBRARY_PATH`?

**Comment by TorbenDyrby** [comment]
Not set, is that Windows?

NITF_PLUGIN_PATH though is set to nitro-nitf\share\nitf\plugins. 

PYTHON_PATH is set to nitro-nitf\share\python. 

Sent from my wireless device

**Comment by JonathanMeans** [comment]
I've uploaded a new installer.

The build system in the 2.8 release is not compatible with Python 3, so you're getting something that's actually a few commits after the release.

If this works for you, and you need it, I can then make an installer for something more identical to the 2.8 release, excepting the build system changes.

**Comment by TorbenDyrby** [comment]
>>> import nitf
Traceback (most recent call last):
  File "C:\apps\nitro-nitf\share\python\nitf\nitropy.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\apps\Miniconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\apps\nitro-nitf\share\python\nitf\__init__.py", line 29, in <module>
    import nitf.nitropy
  File "C:\apps\nitro-nitf\share\python\nitf\nitropy.py", line 17, in <module>
    _nitropy = swig_import_helper()
  File "C:\apps\nitro-nitf\share\python\nitf\nitropy.py", line 16, in swig_import_helper
    return importlib.import_module('_nitropy')
  File "C:\apps\Miniconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_nitropy'

Sent from my wireless device

**Comment by JonathanMeans** [comment]
Can you show me the info line in prints when you first call `python`? (e.g. `Python3.7.0 |Continuum Analytics, Inc.|...`

**Comment by TorbenDyrby** [comment]
(base) C:\Users\td>python
Python 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> 

Sent from my wireless device

**Comment by JonathanMeans** [comment]
I've updated with a new installer.

This will only work with Python 3.6, not 3.7 The build system has not yet been updated to work with the new 3.7 changes, so this is the best I can do for now. 

@asylvest  Would it make sense to do another release once the waf stuff is fixed? Or what's the right way to juggle/prioritize things from here?

**Comment by asylvest** [comment]
Yeah once waf works with 3.7 I'd say let's cut a new minor formal NITRO release.

**Comment by TorbenDyrby** [comment]
We use Python 3.7, so I guess I’ll have to wait. Thanks.
