### ISSUE TITLE
Unable to build in Windows

### ISSUE THREAD

**Issue by Miakonn** [mdaus/nitro#130]
I downloaded the source and installed python. I then entered

python waf configure --enable-debugging --prefix=installed
 can't open file './build/waf': [Errno 2] No such file or directory

I tested creating the build directory and downloading WAF:

mkdir build
curl -o build/waf https://waf.io/waf-2.0.15

Now at least I got WAF to call.

I tested again

python waf configure --enable-debugging --prefix=installed
Traceback (most recent call last):
  File "C:\Repos\nitro-master\build\waf3-2.0.15-ff6573b86ad5ff5d449c8852ad58b8bc\waflib\Scripting.py", line 119, in waf_entry_point
    run_commands()
  File "C:\Repos\nitro-master\build\waf3-2.0.15-ff6573b86ad5ff5d449c8852ad58b8bc\waflib\Scripting.py", line 178, in run_commands
    parse_options()
  File "C:\Repos\nitro-master\build\waf3-2.0.15-ff6573b86ad5ff5d449c8852ad58b8bc\waflib\Scripting.py", line 158, in parse_options
    ctx.execute()
  File "C:\Repos\nitro-master\build\waf3-2.0.15-ff6573b86ad5ff5d449c8852ad58b8bc\waflib\Options.py", line 198, in execute
    super(OptionsContext,self).execute()
  File "C:\Repos\nitro-master\build\waf3-2.0.15-ff6573b86ad5ff5d449c8852ad58b8bc\waflib\Context.py", line 85, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "C:\Repos\nitro-master\build\waf3-2.0.15-ff6573b86ad5ff5d449c8852ad58b8bc\waflib\Context.py", line 126, in recurse
    user_function(self)
  File "C:\Repos\nitro-master\wscript", line 15, in options
    opt.load(TOOLS + ' msvs dumpenv', tooldir='build')
  File "C:\Repos\nitro-master\build\waf3-2.0.15-ff6573b86ad5ff5d449c8852ad58b8bc\waflib\Context.py", line 80, in load
    module=load_tool(t,path,with_sys_path=with_sys_path)
  File "C:\Repos\nitro-master\build\waf3-2.0.15-ff6573b86ad5ff5d449c8852ad58b8bc\waflib\Context.py", line 373, in load_tool
    __import__(tool)
ImportError: No module named 'build'

So, I am not sure I am on the right track. What is the problem?

I am running Windows 10 and hoping to get it to work in Visual Studio 2017.

Please, can anyone help me!

**Comment by hobu** [comment]
This repository is a fork of https://github.com/mdaus/nitro and exists mostly for CMake support. Jump over there and you should be able to get going.

**Comment by JonathanMeans** [comment]
You shouldn't be downloading waf yourself. It comes bundled with the repository and comes with a lot of custom modifications that make it incompatible with the the official release.

It is very unusual that something is looking for `./build/waf`. Can you confirm that this happens right after a clean checkout?

**Comment by Miakonn** [comment]
Thanks for the quick answer. It was my mistake, I accidentally installed Hobu's version. I git cloned the correct version and I got the following instead:
````
C:\Repos\nitro-master>python waf configure --enable-debugging --prefix=installed
Traceback (most recent call last):
  File "C:\Repos\nitro-master\externals\coda-oss\build\waf3-1.7.14-42d4f0bc005284b3bd83b2bd8995addd\waflib\Scripting.py", line 97, in waf_entry_point
    run_commands()
  File "C:\Repos\nitro-master\externals\coda-oss\build\waf3-1.7.14-42d4f0bc005284b3bd83b2bd8995addd\waflib\Scripting.py", line 149, in run_commands
    parse_options()
  File "C:\Repos\nitro-master\externals\coda-oss\build\waf3-1.7.14-42d4f0bc005284b3bd83b2bd8995addd\waflib\Scripting.py", line 127, in parse_options
    Context.create_context('options').execute()
  File "C:\Repos\nitro-master\externals\coda-oss\build\waf3-1.7.14-42d4f0bc005284b3bd83b2bd8995addd\waflib\Options.py", line 134, in execute
    super(OptionsContext,self).execute()
  File "C:\Repos\nitro-master\externals\coda-oss\build\waf3-1.7.14-42d4f0bc005284b3bd83b2bd8995addd\waflib\Context.py", line 84, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "C:\Repos\nitro-master\externals\coda-oss\build\build.py", line 75, in recurse
    super(CPPContext, self).recurse(dirsWithWscripts)
  File "C:\Repos\nitro-master\externals\coda-oss\build\waf3-1.7.14-42d4f0bc005284b3bd83b2bd8995addd\waflib\Context.py", line 125, in recurse
    user_function(self)
  File "C:\Repos\nitro-master\wscript", line 15, in options
    opt.load(TOOLS + ' msvs dumpenv', tooldir='build')
  File "C:\Repos\nitro-master\externals\coda-oss\build\waf3-1.7.14-42d4f0bc005284b3bd83b2bd8995addd\waflib\Context.py", line 81, in load
    fun(self)
  File "C:\Repos\nitro-master\externals\coda-oss\build\build.py", line 728, in options
    opt.load('compiler_cc')
  File "C:\Repos\nitro-master\externals\coda-oss\build\waf3-1.7.14-42d4f0bc005284b3bd83b2bd8995addd\waflib\Context.py", line 81, in load
    fun(self)
  File "C:\Repos\nitro-master\externals\coda-oss\build\waf3-1.7.14-42d4f0bc005284b3bd83b2bd8995addd\waflib\Tools\compiler_c.py", line 39, in options
    opt.load('%s'%x)
  File "C:\Repos\nitro-master\externals\coda-oss\build\waf3-1.7.14-42d4f0bc005284b3bd83b2bd8995addd\waflib\Context.py", line 78, in load
    module=load_tool(t,path)
  File "C:\Repos\nitro-master\externals\coda-oss\build\waf3-1.7.14-42d4f0bc005284b3bd83b2bd8995addd\waflib\Context.py", line 313, in load_tool
    __import__(d)
  File "C:\Repos\nitro-master\externals\coda-oss\build\waf3-1.7.14-42d4f0bc005284b3bd83b2bd8995addd\waflib\Tools\msvc.py", line 106
    except Exception,e:
                    ^
SyntaxError: invalid syntax
````
I am using Python 3.5.4

**Comment by JonathanMeans** [comment]
I'll try to get a fix in for this later today. If you need this sooner, you can switch to Python 2.7

(Most of the work on this library is done in 2.7. 3.x  is largely just supported on an "as problems arise" basis.)

**Comment by JonathanMeans** [comment]
Ok, this is actually a massive pain, and it's going to take a couple days to go through all the waf source code. I'll let you know when it's updated.

**Comment by JonathanMeans** [comment]
@Miakonn Should be fixed now

**Comment by Miakonn** [comment]
Thanks a lot!
