### ISSUE TITLE
Having issues building on macos sierra/anaconda

### ISSUE THREAD

**Issue by tclarke** [mdaus/nitro#22]
I've got the anaconda python distro on OSX sierra with git commit 143b5a7b15482624816cb01cabbc433000f165f6
`python waf configure --require-python --python-dev`

```
Setting top to                           : /Users/tclarke/anaconda/conda-bld/nitro_1476285990341/work 
Setting out to                           : /Users/tclarke/anaconda/conda-bld/nitro_1476285990341/work/target 
Platform                                 : darwin 
Checking for 'gcc' (c compiler)          : /usr/bin/gcc 
Checking for 'g++' (c++ compiler)        : /usr/bin/g++ 
Checking for library pthread             : yes 





About to check

Found it
Checking for compiler flags -m64         : no 
System size                              : 32-bit 
Checking for program ant                 : /usr/local/bin/ant 
Checking for program javac               : /usr/bin/javac 
Checking for program java                : /usr/bin/java 
Checking for program jar                 : /usr/bin/jar 
Checking for program javadoc             : /usr/bin/javadoc 
Java lib/headers                         : set JAVA_HOME in the system environment
(complete log in /Users/tclarke/anaconda/conda-bld/nitro_1476285990341/work/target/config.log) 
Checking for program python              : /Users/tclarke/anaconda/bin/python 
Checking for python version              : 2.7.12 
Checking for library python2.7 in LIBPATH_PYEMBED : not found 
Checking for library python2.7 in LIBDIR          : not found 
Checking for library python2.7 in python_LIBPL    : not found 
Checking for library python2.7 in $prefix/libs    : not found 
Checking for library python2.7m in LIBPATH_PYEMBED : not found 
Checking for library python2.7m in LIBDIR          : not found 
Checking for library python2.7m in python_LIBPL    : not found 
Checking for library python2.7m in $prefix/libs    : not found 
Checking for library python27 in LIBPATH_PYEMBED   : not found 
Checking for library python27 in LIBDIR            : not found 
Checking for library python27 in python_LIBPL      : not found 
Checking for library python27 in $prefix/libs      : not found 
Checking for program /Users/tclarke/anaconda/bin/python-config,python2.7-config,python-config-2.7,python2.7m-config : /Users/tclarke/anaconda/bin/python-config 
Checking for header Python.h                                                                                        : :-( 
Asking python-config for pyembed --cflags flags                                                                     : yes 
Asking python-config for pyembed --libs flags                                                                       : yes 
Asking python-config for pyembed --ldflags flags                                                                    : yes 
Getting pyembed flags from python-config                                                                            : Could not build a python embedded interpreter 
The configuration failed
(complete log in /Users/tclarke/anaconda/conda-bld/nitro_1476285990341/work/target/config.log)
The configuration failed
(complete log in /Users/tclarke/anaconda/conda-bld/nitro_1476285990341/work/target/config.log) (Is python built with -fPIC?)
(complete log in /Users/tclarke/anaconda/conda-bld/nitro_1476285990341/work/target/config.log)
```

Looking at the log, a bunch of config check gcc/g++ builds fail:

```
Checking for compiler flags -m64
==>

int main(int argc, char **argv) {
        (void)argc; (void)argv;
        return 0;
}

<==
[1/2] ^[[32mcxx: target/.conf_check_fc0af2b517b5a3bcae68c9601d515525/test.cpp -> target/.conf_check_fc0af2b517b5a3bcae68c9601d515525/testbuild/test.cpp.1.o
^[[0m
['/usr/bin/g++', '-fPIC', '-Wall', '-Wno-deprecated-declarations', '-O3', '-m64', '-D_FILE_OFFSET_BITS=64', '-D_LARGEFILE_SOURCE', '../test.cpp', '-c', '-o', 'test.cpp.1.o']
[2/2] ^[[33mcxxprogram: target/.conf_check_fc0af2b517b5a3bcae68c9601d515525/testbuild/test.cpp.1.o -> target/.conf_check_fc0af2b517b5a3bcae68c9601d515525/testbuild/testprog
^[[0m
['/usr/bin/g++', '-fPIC', '-Wl,-E', '-m64', 'test.cpp.1.o', '-o', '/Users/tclarke/anaconda/conda-bld/nitro_1476285990341/work/target/.conf_check_fc0af2b517b5a3bcae68c9601d515525/testbuild/testprog']
err: ld: unknown option: -E
clang: error: linker command failed with exit code 1 (use -v to see invocation)

from /Users/tclarke/anaconda/conda-bld/nitro_1476285990341/work: Test does not build: Traceback (most recent call last):
  File "/Users/tclarke/anaconda/conda-bld/nitro_1476285990341/work/externals/coda-oss/build/.waf-1.7.14-6b92f3c95d8c1bad60826036bf26d63f/waflib/Tools/c_config.py", line 459, in run_c_code
    bld.compile()
  File "/Users/tclarke/anaconda/conda-bld/nitro_1476285990341/work/externals/coda-oss/build/.waf-1.7.14-6b92f3c95d8c1bad60826036bf26d63f/waflib/Build.py", line 188, in compile
    raise Errors.BuildError(self.producer.error)
BuildError: Build failed
 -> task in 'testprog' failed (exit status 1):
        {task 4359439440: cxxprogram test.cpp.1.o -> testprog}
['/usr/bin/g++', '-fPIC', '-Wl,-E', '-m64', 'test.cpp.1.o', '-o', '/Users/tclarke/anaconda/conda-bld/nitro_1476285990341/work/target/.conf_check_fc0af2b517b5a3bcae68c9601d515525/testbuild/testprog']

no
from /Users/tclarke/anaconda/conda-bld/nitro_1476285990341/work: The configuration failed
```

It's getting `-Wl,-E` from somewhere and failing because `-E` seems to be a gnu linker option and doesn't work with clang. I can't seem to figure out where it's getting that from. I'm guessing waf is incorrectly guessing those options or has them hard coded.

**Comment by asylvest** [comment]
That `-Wl,-E` is coming from line 899 of `build.py`... we add it if it's not Solaris.  Is there something we can key off of to tell if it's `clang`?  You can put in a pull request in https://github.com/mdaus/coda-oss if you have a proposed fix.

I do recall that one of our users tried to build with clang once and may have gotten farther but ran into some other issues... I don't know how much of a rabbit hole this'll be.  We don't have a specific requirement to support clang, so can't probably devote a ton of resources to this, but if you are able to track down things like this and propose fixes, we can definitely merge those in if they're innocuous.

**Comment by mwysockiMDA** [comment]
I hacked coda-oss to compile on my macbook a few weeks ago, although it was El Capitan instead of Sierra.  I'll try to push a branch out today with my tweaks.

**Comment by tclarke** [comment]
I was able to get it to build by removing the -Wl,-E but that of course breaks it on Linux. I assume you had a better fix? If so, I'll wait for that push.

**Comment by mwysockiMDA** [comment]
Hm, I didn't have a problem with -Wl,-E, so maybe that's only the Sierra version of clang.  I'm actually surprised externals/coda-oss built for you.  One of the first things I had to do was change appleRegex in externals/coda-oss/build/build.py to look for 'darwin' instead of 'i.86-apple-.*'

**Comment by tclarke** [comment]
`./config.guess` gives me `i386-apple-darwin16.0.0`

**Comment by tclarke** [comment]
`ld -E` gives `ld: unknown option: -E` and verified in the man page

**Comment by mwysockiMDA** [comment]
Huh, mine was just 'darwin'.  I'll try to make some time to poke at it tonight when I get home, but if you come up with a fix feel free to do a pull request.  It sounds like my build environment is too different to help much.

**Comment by mwysockiMDA** [comment]
Okay, I double-checked on my laptop at home last night (also tried installing Sierra on my mac mini but that sucker is sloooow).  Waf uses sys.platform from python to determine the build options, and sys.platform should always be just 'darwin' on OS X.  So try changing line 791 in `externals/coda-oss/build/build.py` to be: 
` appleRegex = r'darwin|i.86-apple-.*'`
That was all it took for me to build nitro at home, since it avoids the other parts of coda-oss that doesn't like Macs.
